#!/usr/bin/env python3
"""
build_templates.py - bundle the setup templates into one JavaScript file for the app.

  python build_templates.py [templates_folder] [output_file]

Defaults: app/templates -> app/data/templates.js. A template is a drawing saved from the app,
either as a project file (*.snapparatus.json) or as an exported SVG (the project is embedded in
it). templates.json in the folder lists them in display order:

  [{"file": "reflux.snapparatus.json", "de": "Rückfluss", "en": "Reflux", "start": true}, ...]

"start" marks the template shown on the first visit, when the browser has no drawing saved yet.
Like the device data, the result is a script (window.SNAPPARATUS_TEMPLATES = [...]), because
browsers refuse to load JSON files into a page opened from disk.
"""
import os, sys, re, json, html


def load_project(path):
    text = open(path, encoding='utf-8').read()
    if text.lstrip().startswith('<'):                  # exported SVG with the project embedded
        m = re.search(r'<metadata id="snapparatus">(.*?)</metadata>', text, re.S)
        if not m:
            sys.exit(f'{path}: SVG without Snapparatus project data - export it from the app with "Save as SVG"')
        text = html.unescape(m.group(1))
    data = json.loads(text)
    if data.get('format') != 'snapparatus' or not isinstance(data.get('parts'), list):
        sys.exit(f'{path}: not a Snapparatus drawing')
    return {'parts': data['parts'], 'links': data.get('links', []), 'notes': data.get('notes', [])}


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    src = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, '..', '..', 'app', 'templates'))
    dst = os.path.abspath(sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, '..', '..', 'app', 'data', 'templates.js'))
    index = os.path.join(src, 'templates.json')
    entries = json.load(open(index, encoding='utf-8')) if os.path.exists(index) else []
    listed = {e['file'] for e in entries}
    for f in sorted(os.listdir(src)) if os.path.isdir(src) else []:
        if f != 'templates.json' and f not in listed:
            print(f'  WARN {f} is not listed in templates.json - left out')
    if sum(bool(e.get('start')) for e in entries) > 1:
        sys.exit('only one template can be the start template')
    out = []
    for e in entries:
        tid = re.sub(r'\.(snapparatus\.json|json|svg)$', '', e['file'], flags=re.I)
        out.append({'id': tid, 'de': e['de'], 'en': e.get('en') or e['de'], 'start': bool(e.get('start')),
                    'data': load_project(os.path.join(src, e['file']))})
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, 'w', encoding='utf-8') as f:
        f.write('// Generated by pipeline/scripts/build_templates.py from app/templates - do not edit.\n')
        f.write('window.SNAPPARATUS_TEMPLATES = ')
        json.dump(out, f, ensure_ascii=False, separators=(',', ':'))
        f.write(';\n')
    print(f"{len(out)} templates -> {dst}")


if __name__ == '__main__':
    main()
