#!/usr/bin/env python3
"""
build_app_data.py - bundle the device library into one JavaScript file for the app.

  python build_app_data.py [devices_folder] [output_file]

Defaults: pipeline/out/devices -> app/data/devices.js. The app is opened directly from disk
(file://), where browsers refuse to load JSON files, so the data is a script that assigns
window.SNAPPARATUS_DATA = {categories: [...], devices: [...]}.

Per device: id, category, name, path (catalogue hierarchy), w/h (0.01 mm, scale 1:5),
svg (inner SVG markup: one path plus text labels, no anchor circles), snaps, fill.
"""
import os, sys, re, json, glob

# Catalogue categories of the app, in display order: (key, German, English, palettes)
CATEGORIES = [
    ('flasks', 'Kolben', 'Flasks', ['KOLB-1H', 'KOLB-MH1', 'KOLB-MH2']),
    ('beakers', 'Bechergläser & Erlenmeyer', 'Beakers & Erlenmeyer', ['BECHERGL', 'ERLENMEY']),
    ('condensers', 'Kühler', 'Condensers', ['KUEHLER-1', 'KUEHLER-2']),
    ('distillation', 'Destillation & Aufsätze', 'Distillation & heads', ['DESTIL-1', 'DESTIL-2', 'VERTEIL1']),
    ('adapters', 'Adapter, Schliffe & Stopfen', 'Adapters, joints & stoppers', ['ADAPTER', 'KRUEMM', 'SCHLIFFE', 'STOPFEN']),
    ('funnels', 'Trichter & Filtration', 'Funnels & filtration', ['TRICHTER', 'TROPFTRI', 'TRENNEN1', 'TRENNEN2']),
    ('measuring', 'Messen', 'Measuring', ['MESSZYLI', 'MISCHZYL', 'STANDZYL', 'THERMOM']),
    ('bottles', 'Flaschen & Gaseinleitung', 'Bottles & gas inlet', ['FLASCHEN', 'EINLEIT1']),
    ('heating', 'Heizen & Rühren', 'Heating & stirring', ['HEIZEN-1', 'RUEHREN-1']),
    ('stand', 'Stativ', 'Stand & lab jacks', ['STATMAT1']),
    ('drying', 'Trocknen & Extraktion', 'Drying & extraction', ['TROCKENR', 'TROCKN-1', 'EXTRAKT1', 'DEWARGEF']),
    ('misc', 'Sonstiges', 'Miscellaneous', ['SAMMELSU', 'MINILAB', 'GEFSYMB']),
]


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    src = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, '..', 'out', 'devices'))
    dst = os.path.abspath(sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, '..', '..', 'app', 'data', 'devices.js'))
    cat_of = {p: key for key, de, en, pals in CATEGORIES for p in pals}
    devices = []
    for mf in sorted(glob.glob(os.path.join(src, '*_manifest.json'))):
        pal = os.path.basename(mf)[:-len('_manifest.json')]
        if pal not in cat_of:
            sys.exit(f'palette {pal} has no catalogue category - add it to CATEGORIES')
        for m in json.load(open(mf, encoding='utf-8')):
            svg = open(os.path.join(src, m['file']), encoding='utf-8').read()
            svg = re.sub(r'<circle class="snap"[^>]*/>\n?', '', svg)
            inner = svg[svg.index('>') + 1:svg.rindex('</svg>')].strip()
            devices.append({
                'id': m['id'], 'category': cat_of[pal], 'name': m['name'], 'path': m['path'],
                'w': round(m['w_mm'] * 100), 'h': round(m['h_mm'] * 100),
                'svg': inner,
                'snaps': [{k: v for k, v in s.items() if k != 'width' and v is not None} for s in m['snaps']],
                'fill': m.get('fill'),
            })
    data = {'categories': [{'key': k, 'de': de, 'en': en} for k, de, en, _ in CATEGORIES], 'devices': devices}
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, 'w', encoding='utf-8') as f:
        f.write('// Generated by pipeline/scripts/build_app_data.py - do not edit.\n')
        f.write('// Drawings: LaboBib (c) 1998 Dr. R. Rensch, freeware - see LICENSE-LaboBib.txt\n')
        f.write('window.SNAPPARATUS_DATA = ')
        json.dump(data, f, ensure_ascii=False, separators=(',', ':'))
        f.write(';\n')
    print(f"{len(devices)} devices in {len(CATEGORIES)} categories -> {dst} ({os.path.getsize(dst)/1e6:.1f} MB)")


if __name__ == '__main__':
    main()
